-- MySQL Script generated by MySQL Workbench
-- 02/17/15 15:12:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema librarium
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema librarium
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `librarium` DEFAULT CHARACTER SET utf8 ;
USE `librarium` ;

-- -----------------------------------------------------
-- Table `librarium`.`utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`utente` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `data_registrazione` DATETIME NOT NULL,
  `data_ultimo_accesso` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`cliente` (
  `utente_ID` INT(11) NOT NULL,
  `sesso` TINYINT(1) NULL DEFAULT NULL,
  `data_nascita` DATE NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `numero_telefonico` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`utente_ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_cliente_utente_idx` (`utente_ID` ASC),
  CONSTRAINT `fk_cliente_utente`
    FOREIGN KEY (`utente_ID`)
    REFERENCES `librarium`.`utente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`acquisto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`acquisto` (
  `ID_acquisto` INT(11) NOT NULL AUTO_INCREMENT,
  `data_acquisto` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `incasso` FLOAT NULL DEFAULT NULL,
  `cliente_utente_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID_acquisto`, `cliente_utente_ID`),
  INDEX `fk_acquisto_cliente1_idx` (`cliente_utente_ID` ASC),
  CONSTRAINT `fk_acquisto_cliente1`
    FOREIGN KEY (`cliente_utente_ID`)
    REFERENCES `librarium`.`cliente` (`utente_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`casa_editrice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`casa_editrice` (
  `ID_casa_editrice` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_casa_editrice` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_casa_editrice`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`genere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`genere` (
  `ID_genere` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_genere` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID_genere`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`libro` (
  `ID_libro` INT(11) NOT NULL AUTO_INCREMENT,
  `titolo` VARCHAR(40) NULL DEFAULT NULL,
  `genere_ID_genere` INT(11) NOT NULL,
  `casa_editrice_ID_casa_editrice` INT(11) NOT NULL,
  `costo` FLOAT NULL DEFAULT NULL,
  `disponibilita` INT(11) NULL DEFAULT NULL,
  `flag_ordine` INT(11) NULL DEFAULT NULL,
  `ISBN` VARCHAR(13) NULL DEFAULT NULL,
  `numero_pagine` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_libro`, `genere_ID_genere`, `casa_editrice_ID_casa_editrice`),
  INDEX `fk_libro_genere1_idx` (`genere_ID_genere` ASC),
  INDEX `fk_libro_casa_editrice1_idx` (`casa_editrice_ID_casa_editrice` ASC),
  CONSTRAINT `fk_libro_casa_editrice1`
    FOREIGN KEY (`casa_editrice_ID_casa_editrice`)
    REFERENCES `librarium`.`casa_editrice` (`ID_casa_editrice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_genere1`
    FOREIGN KEY (`genere_ID_genere`)
    REFERENCES `librarium`.`genere` (`ID_genere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`acquisto_has_libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`acquisto_has_libro` (
  `acquisto_ID_acquisto` INT(11) NOT NULL,
  `libro_ID_libro` INT(11) NOT NULL,
  INDEX `fk_acquisto_has_libro_libro1_idx` (`libro_ID_libro` ASC),
  INDEX `fk_acquisto_has_libro_acquisto1_idx` (`acquisto_ID_acquisto` ASC),
  CONSTRAINT `fk_acquisto_has_libro_acquisto1`
    FOREIGN KEY (`acquisto_ID_acquisto`)
    REFERENCES `librarium`.`acquisto` (`ID_acquisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acquisto_has_libro_libro1`
    FOREIGN KEY (`libro_ID_libro`)
    REFERENCES `librarium`.`libro` (`ID_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`addetto_scaffali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`addetto_scaffali` (
  `utente_ID` INT(11) NOT NULL,
  PRIMARY KEY (`utente_ID`),
  INDEX `fk_addetto_scaffali_utente1_idx` (`utente_ID` ASC),
  CONSTRAINT `fk_addetto_scaffali_utente1`
    FOREIGN KEY (`utente_ID`)
    REFERENCES `librarium`.`utente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`addetto_vendite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`addetto_vendite` (
  `utente_ID` INT(11) NOT NULL,
  PRIMARY KEY (`utente_ID`),
  CONSTRAINT `fk_table1_utente1`
    FOREIGN KEY (`utente_ID`)
    REFERENCES `librarium`.`utente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`autore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`autore` (
  `ID_autore` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `cognome` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_autore`))
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`dati_libreria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`dati_libreria` (
  `adm_code` VARCHAR(45) NULL DEFAULT NULL,
  `nomeLibreria` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`libro_has_autore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`libro_has_autore` (
  `libro_ID_libro` INT(11) NOT NULL,
  `autore_ID_autore` INT(11) NOT NULL,
  PRIMARY KEY (`libro_ID_libro`, `autore_ID_autore`),
  INDEX `fk_libro_has_autore_autore1_idx` (`autore_ID_autore` ASC),
  INDEX `fk_libro_has_autore_libro1_idx` (`libro_ID_libro` ASC),
  CONSTRAINT `fk_libro_has_autore_autore1`
    FOREIGN KEY (`autore_ID_autore`)
    REFERENCES `librarium`.`autore` (`ID_autore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_has_autore_libro1`
    FOREIGN KEY (`libro_ID_libro`)
    REFERENCES `librarium`.`libro` (`ID_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`richiesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`richiesta` (
  `ID_richiesta` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_utente_ID` INT(11) NOT NULL,
  `libro_ID_libro` INT(11) NOT NULL,
  `data_richiesta` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_arrivo` DATETIME NULL DEFAULT NULL,
  `flag_inoltro` TINYINT(1) NOT NULL DEFAULT '0',
  `flag_arrivo` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`ID_richiesta`, `cliente_utente_ID`, `libro_ID_libro`),
  INDEX `fk_richiesta_cliente1_idx` (`cliente_utente_ID` ASC),
  INDEX `fk_richiesta_libro1_idx` (`libro_ID_libro` ASC),
  CONSTRAINT `fk_richiesta_cliente1`
    FOREIGN KEY (`cliente_utente_ID`)
    REFERENCES `librarium`.`cliente` (`utente_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_richiesta_libro1`
    FOREIGN KEY (`libro_ID_libro`)
    REFERENCES `librarium`.`libro` (`ID_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `librarium`.`tessera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `librarium`.`tessera` (
  `cliente_utente_ID` INT(11) NOT NULL,
  `codice_tessera` CHAR(6) NOT NULL,
  `punti` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cliente_utente_ID`),
  UNIQUE INDEX `codice_tessera_UNIQUE` (`codice_tessera` ASC),
  CONSTRAINT `fk_tessera_cliente1`
    FOREIGN KEY (`cliente_utente_ID`)
    REFERENCES `librarium`.`cliente` (`utente_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
